#!/usr/bin/env bash

## Author: Nestor
#
## Rofi : Qtile theme selector
#
## Themes
#
## alice 

dir="$HOME/.config/qtile/scripts"
dirthemes="$HOME/.config/qtile/themes"
dircore="$HOME/.config/qtile/core"
theme='window_style'

# CMDs
bodytext="Choose the theme:"

# Options
alice='󰓥 ソードアート・オンライン'
ttgl='󰿗 天元突破グレンラガン'
hack=' コードギアス 反逆のルルーシュ'
nice='󰩃 さくら荘のペットな彼女'
yes=' Yes'
no=' No'

# Interfaz
rofi_cmd() {
	rofi -dmenu \
		-p "$bodytext" \
		-mesg "$bodytext" \
		-theme ${dir}/${theme}.rasi
}

run_rofi() {
	echo -e "$alice\n$ttgl\n$hack\n$nice" | rofi_cmd
}

confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 250px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${dir}/${theme}.rasi
}

confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		killall picom
		if [[ $1 == '--alice' ]]; then
			yes | cp -rf ${dirthemes}/alice/alice.py ${dircore}/theme.py 
			echo -e "export LS_COLORS=\"\$(vivid generate snazzy)\"" >| ~/.config/kitty/.ls_config
			yes | cp -rf ${dirthemes}/alice/picom.conf ~/.config/picom/picom.conf
			ln -sf ~/.config/neofetch/themes/alice ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/Tokyo\ Night\ Storm.conf ~/.config/kitty/theme.conf
			feh --bg-fill --randomize ${dirthemes}/alice/wallpapers/*
		elif [[ $1 == '--ttgl' ]]; then
			yes | cp -rf ${dirthemes}/ttgl/ttgl.py ${dircore}/theme.py 
			echo -e "export LS_COLORS=\"\$(vivid generate lava)\"" >| ~/.config/kitty/.ls_config
			yes | cp -rf ${dirthemes}/ttgl/picom.conf ~/.config/picom/picom.conf
			ln -sf ~/.config/neofetch/themes/ttgl ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/Earthsong.conf ~/.config/kitty/theme.conf
			feh --bg-fill --randomize ${dirthemes}/ttgl/wallpapers/*
		elif [[ $1 == '--hack' ]]; then
			yes | cp -rf ${dirthemes}/hack/hack.py ${dircore}/theme.py 
			echo -e "export LS_COLORS=\"\$(vivid generate catppuccin-frappe)\"" >| ~/.config/kitty/.ls_config
			yes | cp -rf ${dirthemes}/hack/picom.conf ~/.config/picom/picom.conf
			ln -sf ~/.config/neofetch/themes/hack ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/Lavandula.conf ~/.config/kitty/theme.conf
			feh --bg-fill --randomize ${dirthemes}/hack/wallpapers/*
		elif [[ $1 == '--nice' ]]; then
			yes | cp -rf ${dirthemes}/nice/nice.py ${dircore}/theme.py 
			echo -e "export LS_COLORS=\"\$(vivid generate gruvbox-light-hard)\"" >| ~/.config/kitty/.ls_config
			yes | cp -rf ${dirthemes}/nice/picom.conf ~/.config/picom/picom.conf
			ln -sf ~/.config/neofetch/themes/nice ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/gruvbox_light.conf ~/.config/kitty/theme.conf
			feh --bg-fill --randomize ${dirthemes}/nice/wallpapers/*
		fi
		picom --config $HOME/.config/picom/picom.conf &
		sleep 0.5
		sleep 1 && xdotool key --clearmodifiers super+ctrl+r
		#qtile run-cmd qtile cmd-obj -o cmd -f reload_config
		#qtile cmd-obj -o cmd -f reload_config
	else
		exit 0
	fi
}

#Actions
chosen="$(run_rofi)"
case ${chosen} in
	$alice)
		run_cmd --alice
	;;
	$ttgl)
		run_cmd --ttgl
	;;
	$hack)
		run_cmd --hack
	;;
	$nice)
		run_cmd --nice
	;;
esac
