#!/usr/bin/env bash

## Author: Nestor
#
## Rofi : Qtile theme selector
#
## Themes
#
## alice 

dir="$HOME/.config/qtile/themes/script"
theme='window_style'

# CMDs
bodytext="Choose the theme:"

# Options
alice='󰓥 ソードアート・オンライン'
ttgl='󰿗 天元突破グレンラガン'
hack=' コードギアス 反逆のルルーシュ'
nice='󰩃 さくら荘のペットな彼女'
yes=' Yes'
no=' No'

# Commands
cmdalice="echo -e \"from . import alice\nclass Theme(alice.Alice):\n\tpass\" >| ~/.config/qtile/themes/selectedtheme.py";

cmdttgl="echo -e \"from . import ttgl\nclass Theme(ttgl.Ttgl):\n\tpass\" >| ~/.config/qtile/themes/selectedtheme.py";

cmdhack="echo -e \"from . import hack\nclass Theme(hack.Hack):\n\tpass\" >| ~/.config/qtile/themes/selectedtheme.py";

cmdnice="echo -e \"from . import nice\nclass Theme(nice.Nice):\n\tpass\" >| ~/.config/qtile/themes/selectedtheme.py";

# Interfaz
rofi_cmd() {
	rofi -dmenu \
		-p "$bodytext" \
		-mesg "$bodytext" \
		-theme ${dir}/${theme}.rasi
}

run_rofi() {
	echo -e "$alice\n$ttgl\n$hack\n$nice" | rofi_cmd
}

confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 250px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${dir}/${theme}.rasi
}

confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--alice' ]]; then
			eval $cmdalice 
			echo -e "export LS_COLORS=\"\$(vivid generate snazzy)\"" >| ~/.config/kitty/.ls_config
			ln -sf ~/.config/neofetch/themes/alice ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/Tokyo\ Night\ Storm.conf ~/.config/kitty/theme.conf
			qtile run-cmd qtile cmd-obj -o cmd -f reload_config
		elif [[ $1 == '--ttgl' ]]; then
			eval $cmdttgl
			echo -e "export LS_COLORS=\"\$(vivid generate lava)\"" >| ~/.config/kitty/.ls_config
			ln -sf ~/.config/neofetch/themes/ttgl ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/Earthsong.conf ~/.config/kitty/theme.conf
			qtile run-cmd qtile cmd-obj -o cmd -f reload_config
		elif [[ $1 == '--hack' ]]; then
			eval $cmdhack 
			echo -e "export LS_COLORS=\"\$(vivid generate catppuccin-frappe)\"" >| ~/.config/kitty/.ls_config
			ln -sf ~/.config/neofetch/themes/hack ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/Lavandula.conf ~/.config/kitty/theme.conf
			qtile run-cmd qtile cmd-obj -o cmd -f reload_config
		elif [[ $1 == '--nice' ]]; then
			eval $cmdnice 
			echo -e "export LS_COLORS=\"\$(vivid generate gruvbox-light-hard)\"" >| ~/.config/kitty/.ls_config
			ln -sf ~/.config/neofetch/themes/nice ~/.config/neofetch/config.conf
			ln -sf ~/.config/kitty/kitty-themes/themes/gruvbox_light.conf ~/.config/kitty/theme.conf
			qtile run-cmd qtile cmd-obj -o cmd -f reload_config
		fi
	else
		exit 0
	fi
}

#Actions
chosen="$(run_rofi)"
case ${chosen} in
	$alice)
		run_cmd --alice
	;;
	$ttgl)
		run_cmd --ttgl
	;;
	$hack)
		run_cmd --hack
	;;
	$nice)
		run_cmd --nice
	;;
esac
